# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bolt < Formula
  desc "Deploy Terraform Enterprise in a bolt — K8s and Docker, any cloud"
  homepage "https://github.com/sibtihaj/bolt"
  version "0.1.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sibtihaj/bolt/releases/download/v0.1.0/bolt_Darwin_x86_64.tar.gz"
      sha256 "72db4e2164893335b8eb7bf45cb4563bdcc541727cee20f1ebb462c57e9258b6"

      define_method(:install) do
        bin.install "bolt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sibtihaj/bolt/releases/download/v0.1.0/bolt_Darwin_arm64.tar.gz"
      sha256 "ca3f74612b961de8b8a2380ccea8e185d2447d9a0cf0934c9da05254aedaf9a9"

      define_method(:install) do
        bin.install "bolt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sibtihaj/bolt/releases/download/v0.1.0/bolt_Linux_x86_64.tar.gz"
      sha256 "686bb46822e2dcea3457204ba2377f88cdfb668bde8d8ce938a8f93bace7d827"
      define_method(:install) do
        bin.install "bolt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sibtihaj/bolt/releases/download/v0.1.0/bolt_Linux_arm64.tar.gz"
      sha256 "105bb2291544b73fcb92d21dec94709d9de52460837807428505586b8a01dd18"
      define_method(:install) do
        bin.install "bolt"
      end
    end
  end

  test do
    system "#{bin}/bolt", "version"
  end
end
